steps:
- name: 'docker login'
  args: ['docker', 'login', 'asia-northeast3-docker.pkg.dev']
- name: 'docker-build-build-id'
  args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/leejunseok-01-400304/ci-test/adservice:$BUILD_ID', 'src/adservice']
- name: 'docker-build-latest'
  args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/leejunseok-01-400304/ci-test/adservice:latest', 'src/adservice']
- name: 'docker-push-build-id'
  args: ['push', 'asia-northeast3-docker.pkg.dev/leejunseok-01-400304/ci-test/adservice:$BUILD_ID']
- name: 'docker-push-latest'
  args: ['push', 'asia-northeast3-docker.pkg.dev/leejunseok-01-400304/ci-test/adservice:latest']

options:
  logging: 'CLOUD_LOGGING_ONLY'
