steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "asia-northeast3-docker.pkg.dev/leejunseok-01-400304/ci-test/adservice:$SHORT_SHA", "src/adservice"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia-northeast3-docker.pkg.dev/leejunseok-01-400304/ci-test/adservice:$SHORT_SHA"]

options:
  logging: 'CLOUD_LOGGING_ONLY'
