steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "asia-northeast3-docker.pkg.dev/leejunseok-01-400304/ci-test/adservice:$COMMIT_SHA", "src/adservice"]

options:
  logging: 'CLOUD_LOGGING_ONLY'
